
package com.mattiz.ws.test.bean;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "/MattizWebService", targetNamespace = "http:/com.mattiz/wsdl", wsdlLocation = "http://localhost:8080/RestServiceExampleWithJson/webservice/mattiz?wsdl")
public class _002fMattizWebService
    extends Service
{

    private final static URL _002FMATTIZWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mattiz.ws.test.bean._002fMattizWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mattiz.ws.test.bean._002fMattizWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RestServiceExampleWithJson/webservice/mattiz?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RestServiceExampleWithJson/webservice/mattiz?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        _002FMATTIZWEBSERVICE_WSDL_LOCATION = url;
    }

    public _002fMattizWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public _002fMattizWebService() {
        super(_002FMATTIZWEBSERVICE_WSDL_LOCATION, new QName("http:/com.mattiz/wsdl", "/MattizWebService"));
    }

    /**
     * 
     * @return
     *     returns MattizWebService
     */
    @WebEndpoint(name = "MattizWebServicePort")
    public MattizWebService getMattizWebServicePort() {
        return super.getPort(new QName("http:/com.mattiz/wsdl", "MattizWebServicePort"), MattizWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MattizWebService
     */
    @WebEndpoint(name = "MattizWebServicePort")
    public MattizWebService getMattizWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http:/com.mattiz/wsdl", "MattizWebServicePort"), MattizWebService.class, features);
    }

}
