
package com.mattiz.ws.test.bean;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MattizWebService", targetNamespace = "http:/com.mattiz/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MattizWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWelcomeString", targetNamespace = "http:/com.mattiz/wsdl", className = "com.mattiz.ws.test.bean.GetWelcomeString")
    @ResponseWrapper(localName = "getWelcomeStringResponse", targetNamespace = "http:/com.mattiz/wsdl", className = "com.mattiz.ws.test.bean.GetWelcomeStringResponse")
    public String getWelcomeString();

}
