package com.mattiz.persistence.beans;
// Generated 18 Jan, 2014 6:01:04 AM by Hibernate Tools 3.2.2.GA



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String isbn;
     private String title;

    public Book() {
    }

	
    public Book(String isbn) {
        this.isbn = isbn;
    }
    public Book(String isbn, String title) {
       this.isbn = isbn;
       this.title = title;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


