package com.mattiz.persistence.beans;
// Generated 31 Jan, 2012 12:44:20 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BookWithMultipleAuthors generated by hbm2java
 */
public class BookWithMultipleAuthors  implements java.io.Serializable {


     private long isbnCode;
     private String title;
     private Set contributingAuthors = new HashSet(0);

    public BookWithMultipleAuthors() {
    }

    public BookWithMultipleAuthors(String title, Set contributingAuthors) {
       this.title = title;
       this.contributingAuthors = contributingAuthors;
    }
   
    public long getIsbnCode() {
        return this.isbnCode;
    }
    
    public void setIsbnCode(long isbnCode) {
        this.isbnCode = isbnCode;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getContributingAuthors() {
        return this.contributingAuthors;
    }
    
    public void setContributingAuthors(Set contributingAuthors) {
        this.contributingAuthors = contributingAuthors;
    }




}


