package com.mattiz.persistence.beans;
// Generated 31 Jan, 2012 12:44:20 AM by Hibernate Tools 3.2.2.GA



/**
 * ContributingAuthor generated by hbm2java
 */
public class ContributingAuthor  implements java.io.Serializable {


     private long bookId;
     private String firstName;
     private String lastName;
     private BookWithMultipleAuthors bookContributedToByAuthor;

    public ContributingAuthor() {
    }

	
    public ContributingAuthor(BookWithMultipleAuthors bookContributedToByAuthor) {
        this.bookContributedToByAuthor = bookContributedToByAuthor;
    }
    public ContributingAuthor(String firstName, String lastName, BookWithMultipleAuthors bookContributedToByAuthor) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.bookContributedToByAuthor = bookContributedToByAuthor;
    }
   
    public long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public BookWithMultipleAuthors getBookContributedToByAuthor() {
        return this.bookContributedToByAuthor;
    }
    
    public void setBookContributedToByAuthor(BookWithMultipleAuthors bookContributedToByAuthor) {
        this.bookContributedToByAuthor = bookContributedToByAuthor;
    }




}


