<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:mattiz" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:mattiz" xmlns:intf="urn:mattiz" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="returnMessageRequest">

      <wsdl:part name="person" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="returnMessageResponse">

      <wsdl:part name="returnMessageReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="MattizAxisServerImpl">

      <wsdl:operation name="returnMessage" parameterOrder="person">

         <wsdl:input message="impl:returnMessageRequest" name="returnMessageRequest"/>

         <wsdl:output message="impl:returnMessageResponse" name="returnMessageResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="MattizAxisTestSoapBinding" type="impl:MattizAxisServerImpl">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="returnMessage">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="returnMessageRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:mattiz" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="returnMessageResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:mattiz" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="MattizAxisServerImplService">

      <wsdl:port binding="impl:MattizAxisTestSoapBinding" name="MattizAxisTest">

         <wsdlsoap:address location="http://localhost:8080/axis/services/MattizAxisTest"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
